import 'package:flutter/material.dart';
import 'package:flutter/cupertino.dart';
import 'package:sih_ecopreneurs/bookshow.dart';
import 'package:sih_ecopreneurs/autogenerated.dart';

import 'dart:convert';
import 'package:http/http.dart' as http;


class ListScreen extends StatefulWidget {
  final String category;
  final String subcategory;
  const ListScreen({super.key, required this.category, required this.subcategory});

  @override
  State<ListScreen> createState() => _ListScreenState();
}

class _ListScreenState extends State<ListScreen> {

List<Book> books = [];

Future<List<Book>> fetchBooks() async {
  final response = await http.get(
    Uri.parse('https://script.googleusercontent.com/macros/echo?user_content_key=oGFMhML7Uxgmk_fqwS6yLEu5xa5Vt4YFxe9LCyJ7pWyOK9qpJUzVtDIPgRqNAsxqklds_TZtZ4qJdbmnhtI0dfSmhUcCpQHQm5_BxDlH2jW0nuo2oDemN9CCS2h10ox_1xSncGQajx_ryfhECjZEnCYeyrODuYwlFVuUQVZfrKqejKMycKQY5Ko-AsQn0VDu_N93VfzDp0p32pziMZ5ytshrkaDr_l6VCGZl6SMNQVUTVYPRCViul9z9Jw9Md8uu&lib=MCyoCx4Qt_Jh7a1mH3iRxt4AnPvVPRreW',
  ));

  if (response.statusCode == 200) {
    final List<dynamic> data = json.decode(response.body);
    return data.map((json) => Book.fromJson(json)).toList();
  } else {
    throw Exception('Failed to load books');
  }
}

  @override
  void initState() {
    super.initState();
    fetchBooks().then((val) {
      setState(() {

       books = val;
      });
    });
    print(books);
  }

  bool showSearchBar = false;
  TextEditingController _searchController = TextEditingController();

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: Text('${widget.category} : ${widget.subcategory}'),elevation: 0,foregroundColor:Colors.black, backgroundColor:Color(0xfffeebdc),actions: <Widget>[

        IconButton(
          iconSize: 36,
          icon: const Icon(CupertinoIcons.cart, color: Colors.black),
          onPressed: () {

          },
        ),
        AnimatedSwitcher(
          duration: Duration(milliseconds: 200),
          child: showSearchBar
              ? Container(
            key: ValueKey<int>(1),
            width: 200,
            child: TextField(
              controller: _searchController,
              autofocus: true,
              decoration: InputDecoration(
                hintText: 'Search...',
                border: InputBorder.none,
              ),
            ),
          )
              : IconButton(
            key: ValueKey<int>(2),
            icon: Icon(Icons.search),
            onPressed: () {
              setState(() {
                showSearchBar = true;
              });
            },
          ),
        ),

      ], ),
      body: ListView.builder(
        itemCount: books.length, // Adjust the number of cards as needed
        itemBuilder: (context, index) {
          return GestureDetector(onTap: () {
            Navigator.of(context).push(MaterialPageRoute(builder: (context) => BookShow(name: books[index].name,crossprice: books[index].externalPrice.toString(), price: books[index].price.toString())));
          },child:Container(
            padding: EdgeInsets.all(1),
            margin: EdgeInsets.symmetric(vertical: 8.0),
            child: Column(
              children: [
                Container(
                  height: 200.0, // Adjust the height of the image
                  decoration: BoxDecoration(
                    image: DecorationImage(
                      image: AssetImage('assets/images/buk.png'), // Replace with your image URL
                      fit: BoxFit.cover,

                    ),
                  ),
                ),
                SizedBox(height: 8.0),
                Padding(
                  padding: const EdgeInsets.all(8.0),
                  child: Column(
                    crossAxisAlignment: CrossAxisAlignment.start,
                    children: [
                      Text(
                        books[index].name,
                        style: TextStyle(
                          fontSize: 18.0,
                          fontWeight: FontWeight.bold,
                        ),
                      ),
                      SizedBox(height: 8.0),
                      Row(
                        mainAxisAlignment: MainAxisAlignment.spaceBetween,
                        children: [
                          Text(
                            'INR ${books[index].price}', // Replace with the actual price
                            style: TextStyle(
                              color: Colors.grey,
                            ),
                          ),
                          ElevatedButton(
                            onPressed: () {
                              // Handle add to cart button press
                              print('Add to Cart pressed');
                            },
                            style: ElevatedButton.styleFrom(
                              primary: Colors.red,
                            ),
                            child: Text('Add to Cart'),
                          ),
                        ],
                      ),
                    ],
                  ),
                ),
              ],
            ),)
          );
        },
      ),
    );
  }
}

class ProductCard extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return GestureDetector(onTap: () {
     // Navigator.of(context).push(MaterialPageRoute(builder: (context) => BookShow(name: 'product title', price: '1700')));
    },child:Container(
      padding: EdgeInsets.all(1),
      margin: EdgeInsets.symmetric(vertical: 8.0),
      child: Column(
        children: [
          Container(

            height: 200.0, // Adjust the height of the image

          ),
          SizedBox(height: 8.0),
          Padding(
            padding: const EdgeInsets.all(8.0),
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                Text(
                 'adas',
                  style: TextStyle(
                    fontSize: 18.0,
                    fontWeight: FontWeight.bold,
                  ),
                ),
                SizedBox(height: 8.0),
                Row(
                  mainAxisAlignment: MainAxisAlignment.spaceBetween,
                  children: [
                    Text(
                      '', // Replace with the actual price
                      style: TextStyle(
                        color: Colors.grey,
                      ),
                    ),
                    ElevatedButton(
                      onPressed: () {
                        // Handle add to cart button press
                        print('Add to Cart pressed');
                      },
                      style: ElevatedButton.styleFrom(
                        primary: Colors.red,
                      ),
                      child: Text('Add to Cart'),
                    ),
                  ],
                ),
              ],
            ),
          ),
        ],
      ),)
    );
  }
}
